### PR TITLE
Upgrade to ruby 2.2 and rails 4.2.2

### PR DESCRIPTION
**Pull request by varunlalan**

### CODE REVIEW

**Comment by rohandaxini** [comment]
@varunlalan :+1: 
Will start reviewing this soon.

**Comment by rohandaxini** [comment]
okay time to merge this PR soon now @varunlalan ill do so

**Comment by rohandaxini** [comment]
@varunlalan can u rebase this branch with master once ?

**Comment by varunlalan** [comment]
Sure @rohandaxini

**Comment by varunlalan** [comment]
@rohandaxini Branch rebased with `master`.

**Pull request merged**
