### PR TITLE
Hound custom configuration added

### PR DESCRIPTION
**Pull request by Darshan-Chauhan**
Hi team,
This PR adds some custom configuration for Hound.
Trello link: https://trello.com/c/8kSCUHet/54-configure-hound

Please review it and let me know if any further changes are required.
Thnx.

### CODE REVIEW

**Comment by rohandaxini** [comment]
@sampatbadhe @rohanpujaris is this PR good to merge ?

**Comment by rohanpujaris** [comment]
@Darshan-Chauhan, Have you tested this code. Please test this code by making dummy commits. Also verify that do we need all the config. Can't we just paste the config that we need.

cc: @rohandaxini, @sampatbadhe

**Comment by Darshan-Chauhan** [comment]
@rohanpujaris , sure I'll check it

**Comment by Darshan-Chauhan** [comment]
I've checked the Hound custom configuration, It's working.
And we've to keep all the configuration. If we don't than it doesn't give warnings.

**Comment by rohanpujaris** [comment]
Thanks for verifying @Darshan-Chauhan. PR :+1:

**Pull request merged**
