### PR TITLE
Solr search fixes for underscores and hyphens

### PR DESCRIPTION
**Pull request by Darshan-Chauhan**
Hello Team,

This PR removes bug => Few posts are not properly searchable using underscores.
Ticket link: https://trello.com/c/eLL553gw/50-bug-few-posts-are-not-properly-searchable-using-underscores

Please review and let me know if any changes are required.

Thanks

### CODE REVIEW

**Comment by karanvalecha** [comment]
:+1:

**Comment by rohandaxini** [comment]
@Darshan-Chauhan thanks, for this PR to work smoothly in prod, do we need any PROD chores to re-index entire database again? OR the schema changes you did will take care of everything without re-indexing entire database ?

**Comment by Darshan-Chauhan** [comment]
@rohandaxini no need to re-index database again.

**Comment by rohanpujaris** [comment]
:+1:

**Pull request merged**
