### PR TITLE
Exclude draft posts from tag search

### PR DESCRIPTION
**Pull request by sampatbadhe**
Hello Team,

This PR will exclude draft posts from search by tag click.

Please review and advice.

Thanks.

### CODE REVIEW

**Comment by swatijadhav** [comment]
@sampatbadhe :+1:

**Comment by chinmaydalvi** [comment]
:+1:

**Comment by rohandaxini** [comment]
@sampatbadhe good catch and fix. Thanks for doing it proactively :+1:

**Comment by titame** [comment]
:+1:

**Comment by rohanpujaris** [comment]
:+1:

**Comment by abhijitsinha** [comment]
:+1:

**Comment by rohandaxini** [comment]
@sampatbadhe this is deployed to production now. Can u check / test once and let me know if all is fine ?

**Comment by sampatbadhe** [comment]
Hello @rohandaxini 

I tested it on production working fine now. Thanks.

**Pull request merged**
