### PR TITLE
Modify top contributors rule

### PR DESCRIPTION
**Pull request by titame**
Hi Team,

This PR has changes in logic of pulling top contributors within specified time span. Please review and let me know if any changes are required.

Thanks,
Tushar Titame

### CODE REVIEW

**Comment by rohandaxini** [comment]
@titame I deployed this to prod and this is what it shows me now in Knowbuddy prod app. "Top Contributors" section is empty now. Am I missing anything ?
cc: @swatijadhav 

screen shot 2015-06-10 at 9 58 16 am

**Comment by swatijadhav** [comment]
@rohandaxini In the recent changes, the top contributors are based on the posts added in last 7 days and as we can see here the latest post is around "23 days ago" i.e. no posts in last 7 days.
Hence the top contributors section is empty here.

One thing we can do here is, we can fetch top contributors on iterations. For ex: if no posts in last 1 week, then fetch posts in last 2 weeks. If still no posts, then fetch in last 3 weeks and so on.
Or we can just make it "last week" -> "last month" -> "last quarter"..

Let us know your thoughts. Thanks.

**Comment by rohandaxini** [comment]
@swatijadhav yes I agree. If no posts in last 1 week then pull for last 2 weeks, last 3 weeks and so on.

**Comment by rohandaxini** [comment]
@swatijadhav yes if its not present for last 1 week, then last 1 month and last quarter. I suspect what if we get just 1 contributor for last 1 week / 1 month ? Atleast it should show last top 3 contributors.

**Comment by swatijadhav** [comment]
Sure @rohandaxini.
We will keep iterations as "last week" -> "last month" -> "last quarter" and fetch atleast 3 contributors. 
Thanks.

**Comment by titame** [comment]
Sure @rohandaxini.

**Pull request merged**
