### PR TITLE
Upgrading to rails 4

### PR DESCRIPTION
**Pull request by namrataukirde**
Hello Team, 
    This branch has changes for upgrading rails and ruby. Please review it and let me know if any changes are required.

completed with-
  - [x] Upgrading from rails 3.2.17 to rails 4.1.8
  - [x] Used ruby 2.1.5 version

Thanks,
Namrata

### CODE REVIEW

**Comment by rohandaxini** [comment]
Thanks @namrataukirde lot of hound notifications. Could @amolshinde or you fix them?

**Comment by rohandaxini** [comment]
@amolshinde can u try Ruby 2.2.0 and see if it affects anything ?

**Comment by rohandaxini** [comment]
@amolshinde may be you can create a separate branch to upgrade to Ruby 2.2 and work separately on the upgrade. For now this PR fro  @namrataukirde is fine.

**Comment by amolshinde** [comment]
Sure @rohandaxini

**Comment by namrataukirde** [comment]
Sure @rohandaxini , I am fixing hound notifications.

**Comment by rohandaxini** [comment]
@namrataukirde @amolshinde, is this branch good to merge and test ?

**Comment by swatijadhav** [comment]
@rohandaxini This PR is now good to merge. Thanks.

**Comment by rohandaxini** [comment]
Nice. thanks @swatijadhav

**Pull request merged**
