### PR TITLE
Fix UI styles

### PR DESCRIPTION
**Pull request by varunlalan**
Fixed few UI issues - 

* Post box styling was not appearing on Firefox (Ubuntu).

Before:
selection_079

Now:
selection_080

* Edit post didn't had box border.

Before:
selection_082

Now:
selection_083

* Uploading invalid file displayed alert but didnt hide loading indicator after closing alert box.

selection_084

### CODE REVIEW

**Comment by rohandaxini** [comment]
:+1: 
reviewing now

**Comment by rohandaxini** [comment]
@varunlalan ill review and merge this PR

**Comment by rohandaxini** [comment]
@varunlalan I deployed this to prod now, can you review / recheck / test once if its all fine on Firefox now?

**Comment by varunlalan** [comment]
@rohandaxini I tested fixed bugs on firefox. Looks fine now.

**Pull request merged**
